[package]
name = "webauth"
version = "0.1.0"
authors = ["Lewin Probst <info@emirror.de>"]
edition = "2021"

[dependencies]
naphtha = { path = "../modcol/naphtha", features = ["database"] }
serde = { version = "^1.0.118", features = ["derive"]}
jsonwebtoken = "7.2.0"
rocket = "0.4.6"
dotenv = "0.15.0"
chrono = "^0.4.19"
enum_derive = "0.1.7"
