[package]
name = "rocket-airport"
version = "0.2.0-dev"
authors = ["Lewin Probst <info@emirror.de>"]
edition = "2021"

[dependencies]
anyhow = "1"
argon2 = "0.5.3"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
log = "0.4"
rand = "0.8"
rocket = { version = "0.5", features = ["secrets"] }
