[package]
name = "rocket-webauth"
version = "0.2.0-dev"
authors = ["Lewin Probst <info@emirror.de>"]
edition = "2021"

[dependencies]
anyhow = "1"
jsonwebtoken = "7.2.0"
rocket = "0.5"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
argon2 = "0.5.3"
