[package]
name = "simple"
version = "0.1.0"
edition = "2021"
description = "Simple example to create a login with cosmodrome"

[dependencies]
anyhow = "1"
log = "0.4"
rocket = { version = "0.5", features = ["json"] }
cosmodrome = { path = "../../" }
